# ========================
# SERVER CONFIGURATION
# ========================
spring.application.name=docflow
server.port=8080

# ========================
# DATABASE CONNECTION
# ========================
# Tells Spring Boot WHERE to find the database
spring.datasource.url=jdbc:postgresql://localhost:5432/docflow

# Login credentials (same password we used in docker run)
spring.datasource.username=postgres
spring.datasource.password=docflow123

# ========================
# JPA / HIBERNATE
# ========================
# "update" means: if the table doesn't exist, create it.
# If it exists, update its structure to match the Entity class.
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console (helpful for learning!)
spring.jpa.show-sql=true

# Format the SQL so it's readable
spring.jpa.properties.hibernate.format_sql=true
