# ========================
# SERVER CONFIGURATION
# ========================
spring.application.name=docflow
server.port=8080

# ========================
# DATABASE CONNECTION
# ========================
# Tells Spring Boot WHERE to find the database
spring.datasource.url=jdbc:postgresql://localhost:5432/docflow?TimeZone=UTC

# Login credentials (same password we used in docker run)
spring.datasource.username=postgres
spring.datasource.password=docflow123

# ========================
# JPA / HIBERNATE
# ========================
# "update" means: if the table doesn't exist, create it.
# If it exists, update its structure to match the Entity class.
spring.jpa.hibernate.ddl-auto=update

# Explicitly tell Hibernate we are using PostgreSQL
# Why: Hibernate tries to auto-detect the database by connecting first.
# If that fails, it throws the "Unable to determine Dialect" error.
# This line tells it upfront: "We're using PostgreSQL, no need to detect."
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# Fix: Windows uses "Asia/Calcutta" but PostgreSQL 16 only knows "Asia/Kolkata"
# UTC is a universal timezone that every system understands, so we use that.
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Show SQL queries in the console (helpful for learning!)
spring.jpa.show-sql=true

# Format the SQL so it's readable
spring.jpa.properties.hibernate.format_sql=true

# ========================
# SWAGGER / API DOCS
# ========================
# Path where the raw OpenAPI JSON spec is served
springdoc.api-docs.path=/v3/api-docs
# Path for the Swagger UI  
springdoc.swagger-ui.path=/swagger-ui.html
# Resolve JWT security issues with Springdoc
springdoc.swagger-ui.disable-swagger-default-url=true

